apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx-dinesh
    image: nginx:1.21.3
    ports:
    - containerPort: 8080
  - name: nginx
    image: afakharany/watcher
    ports:
    - containerPort: 8080
    
