apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-dinesh
    image: nginx
    ports:
    - containerPort: 8080
  - name: nginx
    image: afakharany/watcher
    ports:
    - containerPort: 8080
    
